version: "2.2"
services:
  share:
    volumes:
      - ./authorized_keys:/home/galqiwi/.ssh/authorized_keys
      - /home/galqiwi/.vbox-personal-share/:/share
    network_mode: "host"
    build: .
    restart: always
